[Refactor] QuizCreateForm 컴포넌트
prgrms-fe-devcourse/FEDC2_CheQuiz_Gidong pull request #173
Opened 2022-10-20 02:37 UTC by Outwater

## 📌 PR 설명

하루에 1시간씩이라도 점진적으로 코드 리팩토링 해보려고 합니다.
기존 컴포넌트 하나씩, 가독성 및 변경된 컨벤션 적용 후에,
퀴즈 생성 추가 기능 구현해볼게요~

## 💻 요구 사항과 구현 내용

- 폴더/파일 컨벤션 맞추기 위해 QuizCreateForm, style.ts, index.ts 로 컴포넌트 관리
- interfaces/model.ts 만들어, 공통적으로 사용되는 모델에 대한 interface 정의
- `_id` 를 어쩔 수 없이 사용해야하기 때문에, eslintrc에서 underscore를 허용해주는 옵션 추가
## ✔️ PR 포인트 & 궁금한 점

고민이 되었던 포인트가 2가지가 있는데,
첫 번째는 하위컴포넌트의 위치인데, QuizCreateForm을 구성하는 QuizSetForm,  QuizList, QuizItem, ... 이 존재합니다.
원래 정했던 컨벤션에 따르면, 이 컴포넌트들이 전부 'components/ -' 1 depth에 위치하여야하는데, 아무리 생각해도 특정 컴포넌트에 속해있다면, 해당 컴포넌트 하위에 위치하는게 맞지 않나라는 생각이 드네요~
1. `components/QuizCreateForm`, `components/QuizList`, `components/QuizItem` ,...
2. `components/QuizCreateForm`, `QuizCreateForm/QuizList`, `QuizCreateForm/QuizItem` 

두 번째는, interface 정의 위치에 대한 고민입니다.
interface 폴더 및 d.ts 파일을 사용하지 않기로 결정했었는데,
앱 전반에서 공통적으로 사용되고 있는 model에 대한 interface의 정의 위치가 어디가 되어야하는가 고민이 있었습니다.
우선은 interfaces/model.ts 를 만들어, 최소한의 전역 interface를 정의하였는데, 관련 의견 궁금하네용.

2022-10-20 06:34 UTC, mrbartrns commented
리뷰하기 전에 한가지 제안드립니다!
저번에 창민님이랑 eslint rule 중 `@typescript-eslint/no-floating-promises` 를 off 하기로 했었는데, 이 부분 추가해서 반영해주실 수 있나요?
감사합니다 :)

2022-10-20 11:46 UTC, mrbartrns requested changes
인수님 리뷰 마쳤습니다.
순환 참조가 일어나는 부분을 수정해주시면 감사하겠습니다.
모델 부분도 인터페이스를 정의해주셔서, 유용하게 사용할 수 있을 듯 합니다!

고생하셨습니다!

2022-10-20 11:46 UTC, mrbartrns commented on .eslintrc
> +    ],
p3) 포맷 맞춰주신거 좋습니다 👍

2022-10-20 11:46 UTC, mrbartrns commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +}
p1) `./api/create`에서는 QuizSetType을 참조하고, `./api/create`로부터 QuizItemType을 참조하는 순환 참조가 발생하는 듯 합니다!

타입들을 일단은 한 곳에 모아두는 것은 어떻게 생각하시나요?

2022-10-20 11:46 UTC, mrbartrns commented on src/components/QuizCreateForm/QuizCreateForm.tsx
>    const [isSet, toggleSet] = useState<boolean>(false);
p3) useState(false) 이 부분은 타입스크립트에서 타입을 자동으로 잡아 주기 때문에 boolean은 붙이지 않아도 됩니다 :)

2022-10-20 11:46 UTC, mrbartrns commented on src/interfaces/model.ts
> +export interface User {
p3) good goood 👍

2022-10-21 01:05 UTC, Outwater commented on src/components/QuizCreateForm/QuizCreateForm.tsx
>    const [isSet, toggleSet] = useState<boolean>(false);
그렇군요 : ) 해당 부분 수정 완료했습니다.

2022-10-21 01:06 UTC, Outwater commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +}
네 일단 순환참조를 떠나서, custom Type들도 model.ts에 두는 것이 맞다고 생각하였고, 그에 따라 순환참조 문제도 자연스럽게 해결되네요.

2022-10-21 01:10 UTC, loopy-dev approved these changes

2022-10-24 06:50 UTC, chmini reviewed
PR 확인했어요 :)
늦어진 점 죄송합니다

파일 구조 같은 경우는 인수님 말씀처럼 변경해도 저는 좋습니다
다만 조금 더 구체적인 표현을 가져와보자면 Page 컴포넌트와 1대1 매칭되는 형태로 가도 좋을 것 같습니다
예를 들어 `pages/QuizCreate` 컴포넌트라면 이 페이지 내부에서 쓰이는 컴포넌트를 `components/QuizCreate` 에 두는 형태를 의미합니다

2022-10-24 06:50 UTC, chmini commented on src/interfaces/model.ts
> +export interface QuizSetType {
`P2` @Outwater @mrbartrns 

>`type` 을 사용해야하는 경우는 제외하고 네이밍 규칙으로 **`type postfix`** 를 사용한다

이 내용에 근거해서 postfix를 붙인거죠?
이거 혹시 위와 같은 규칙을 정한 이유가 무엇이었는지 알 수 있을까요?
기억이 안 나네요.. ㅠ

2022-10-24 06:50 UTC, chmini commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
`P2`

저희가 스타일드 컴포넌트 파일 분리를 유지하기로 했었나요? 아니면 해제하기로 했었나요?

2022-10-24 09:08 UTC, mrbartrns commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
해제 하기로 했었는데, 당장 해제할 필요는 없어 보여요. 차근 차근 진행하면 될것 같습니당 @chmini

2022-10-24 09:08 UTC, mrbartrns commented on src/interfaces/model.ts
> +export interface QuizSetType {
@chmini 창민님이 말씀하신 부분이 맞아요ㅋㅋ

2022-10-25 07:27 UTC, Outwater commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
아 해제 하기로 했었네요. 사실은 저는 그 때 말씀드린 것 처럼 styledcomponent를 하나의 파일에서 가장 아래 부분에 두는 것을 시도해보고 싶기는 한데, 다 같이 합의가 안된 부분이라 우선은 분리하여 진행했습니다.
그 때 당시에도 하나의 파일에서 공간적인 분리를 통한 방법 ( 타입-로직-스타일)에 대해 공감하셨는데, 에러로 인해 합의된 rule에 반영하지 못했던 것으로 알고 있는데
해당 부분 해결되었는데(eslint 옵션을 통해), 전체적인 rule에 추가하고 진행해도 될지 의견 궁금합니다. 
@mrbartrns @chmini

2022-10-25 07:32 UTC, Outwater commented
> 

페이지를 기준으로 components를 구분하는 것도 좋은 아이디어네요!
컴포넌트의 수도 어느정도로 제한적이 될 수 있고, 컴포넌트들의 도메인 유사성도 가질 수 있구요.
형식적으로는 1depth를 유지할 수 있으니 컴포넌트를 찾는 것에도 적합하다고 생각이 드네요.
반영해보도록 하겠습니다! 감사합니다.

2022-10-25 07:34 UTC, Outwater commented on src/interfaces/model.ts
> +export interface QuizSetType {
@chmini 저도 생각은 나지 않는데, 아마 -type을 사용하는 사람도 있고, 사용하지 않는 사람도 있기 때문에 통일성을 주기 위해서 postfix Rule을 설정해두었던 것으로 알고 있습니다.

2022-10-25 07:38 UTC, mrbartrns commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
그 부분은 이미 추가되어 있습니다. `"@typescript-eslint/no-use-before-define": "off",` 이 부분이 해당 옵션입니당

2022-10-25 07:41 UTC, Outwater commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
추가는 되어 있는데, 그렇게 사용한다고 합의는 하지 않아서 반영하지 않았었습니당.
준혁님은 '.styles.ts' 파일로의 분리가 아닌 '타입-로직-스타일'을 하나의 파일에 작성하는 방식에 대해 ok라고 생각하면 될까요?

2022-10-25 07:43 UTC, mrbartrns commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
네넵 해당 부분처럼 작성하는 방식에 동의합니다. 여담으로 다른 프로젝트에서 해당 형식으로 작성중인데, 개인적으로는 훨씬 좋은 것 같아요!

2022-10-25 07:55 UTC, chmini commented on src/interfaces/model.ts
> +export interface QuizSetType {
@Outwater @mrbartrns 
이 룰을 저는 type 관련해서 postfix를 붙이는 것이 아니라 interface에만 붙이는 것은 별로라고 생각하는데 여러분들은 어떠신가요?
저는 개인적으로 postfix를 안붙이고 싶긴 합니다 ㅎㅎ

2022-10-25 08:01 UTC, chmini commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
@Outwater
저도 파일 내부에서의 코드 분리 방식 좋아요
그런데 다만 린트 룰을 끔으로써 적용시키는 것이 괜찮은지는 잘 모르겠습니당

2022-10-25 08:03 UTC, chmini commented
@mrbartrns 
준혁님도 Page 컴포넌트와 1대1 매칭에 대해서 어떻게 생각하시는지 궁금해요
괜찮다고 생각되시면 요것을 적용하는 방향으로 마무리해두는 것도 좋을 것 같아요

2022-10-25 08:43 UTC, Outwater commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
@chmini  린트 룰을 끄지 않고, 스타일드 컴포넌트를 파일 아래에 선언하여 사용할 수 있는 방법이 있을까요?
파일내부 & 스타일드 컴포넌트를 파일 상단 부에 위치시키는 것은, 스타일드 컴포넌트의 길이를 예측할 수 없고 주요 로직 접근의 방해가 크기 때문에 지양하고 있습니다.

2022-10-25 08:47 UTC, Outwater commented on src/interfaces/model.ts
> +export interface QuizSetType {
저도 postfix가 필요한 이유가 명확한 것이 아니라면, 해당 룰 제외에 한 표를 던집니다.
@mrbartrns 의견 일치하면 바로 룰 수정 및 적용 가시죠.

2022-10-25 08:49 UTC, mrbartrns commented on src/interfaces/model.ts
> +export interface QuizSetType {
넵 좋습니다.

2022-10-25 08:50 UTC, loopy-dev commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
저도 다른 프로젝트들을 참고했었는데 해당 룰을 사용하는 프로젝트들이 생각보다 많았고, 바벨에서 컴포넌트로 변환하는 과정을 거치기 때문에 lint rule을 끄지 않는게 크게 의미가 없다고 생각합니다

2022-10-25 08:52 UTC, mrbartrns commented
@chmini `components/QuizCreateForm` 폴더 하위 폴더에 `QuizSetForm.tsx` 형식으로 넣어둔다는 말씀이신가요?

2022-10-25 08:55 UTC, Outwater commented
> @mrbartrns  `components/QuizCreateForm` 폴더 하위 폴더에 `QuizSetForm.tsx` 형식으로 넣어둔다는 말씀이신가요?

page마다 components 폴더를 하나씩 만드는 것이니까
components/QuizCreate/QuizCreateForm, components/QuizCreate/QuizList , ... 들어오는 형식이네요!

2022-10-25 09:12 UTC, chmini commented on src/interfaces/model.ts
> +export interface QuizSetType {
@Outwater @mrbartrns 
그러면 이 건은 postfix 해제로 마무리하고 코멘트 닫겠습니다
노션도 수정해둘게요!

2022-10-25 09:18 UTC, chmini commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
@mrbartrns 
다른 프로젝트에서 해당 룰을 사용한다는 것은 린트 룰을 끈다는 거죠?
그리고 결론은 꺼야한다가 맞을까요?

@Outwater 
넴 말씀하신 부분은 저번에도 들어서 이해하고 있어요
저도 끄는 것에 거부감이 있는 것은 아니지만 린트 룰 자체가 호이스팅을 하지 말자라서 저희가 하고자하는 코드 스타일을 위해 꺼도 되나 싶어서하는 작은 염려?정도입니당 :)

준혁님이 꺼야한다가 결론이 맞다면 끄고 변경하는 것으로 마무리해도 될 것 같은데 다들 괜찮나요?

2022-10-25 09:23 UTC, loopy-dev commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
@chmini  해당 룰을 사용한다는 것은 lint rule을 off 처리한다는 것이 맞습니다.
호이스팅 관련 여부는, 우리가 하나의 파일당 하나의 컴포넌트 및 하나의 함수 원칙을 준수한다면 큰 문제는 없을 것 같아요.

2022-10-25 09:24 UTC, chmini commented
> `components/QuizCreateForm` 폴더 하위 폴더에 `QuizSetForm.tsx` 형식으로 넣어둔다는 말씀이신가요?

제가 이야기한 것은 이 부분은 아닌 것 같은데.. 
인수님이 설명해주신 것과 같이 `pages/QuizCreate` 가 있다면 `components/QuizCreate` 폴더를 만들고 이 폴더의 하위로 QuizCreate **페이지**를 구성하는 컴포넌트를 넣는다는 말입니당 👍🏻 

혹시 준혁님이 말씀하신 것은 1대1 매칭된 컴포넌트 폴더 내부에서 depth를 더 가져가자는 말씀이신가요?

2022-10-25 09:27 UTC, mrbartrns commented
@chmini 제가 생각한 구조는, 
`QuizCreatePage`라는 Page 컴포넌트(`QuizCreatePage.tsx`)가 있을 때, 

components
|-- QuizCreatePage
|----QuizSetForm.tsx
|---QuizList.tsx
이런 형식으로 간다고 이해했는데, 제가 이해한 부분과 다른 점이 있을까요?

2022-10-25 09:36 UTC, chmini commented
@mrbartrns 
오 네 그 구조 맞아요 👍🏻 
그런데 예시 들어주실 때 QuizCreateForm 안에 QuizSetForm을 넣는다고 해서 `components/QuizCreatePage` 에서 하위로 하나 더 넣는다는 의미인 줄 알았어요

2022-10-25 09:47 UTC, chmini commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
@mrbartrns 
네 ㅎㅎ 그럼 이 부분은 린트 룰을 끄고 가는 것으로 결론짓고 넘어가면 좋을 것 같습니다

2022-10-25 09:47 UTC, chmini commented on src/components/QuizCreateForm/QuizCreateForm.tsx
> +import * as S from './QuizCreateForm.styles';
이 코멘트 닫을게요

2022-10-25 09:49 UTC, chmini approved these changes
무한 API 요청 문제가 해결되고 머지하는 것이 좋다고 생각해요
하지만 일단 Approve는 해두겠습니다

2022-10-25 10:09 UTC, mrbartrns commented
@chmini 무한 요청 관하여, 어떠한 부분에서 문제가 되는지 이슈에 남겨주실 수 있나요? 제 환경(노트북, 데스크롭 회원가입, 로그인 성공, 로그인 실패시)에서 테스트 결과, 요청 관련하여 무한 요청 현상이 발생하지 않았습니다.

2022-11-02 02:13 UTC, merged